"""
Utilities for displaying DataFrames visually in the terminal using tabulate.
"""

import pandas as pd
from tabulate import tabulate
from typing import Optional


def print_dataframe_head(
    df: pd.DataFrame,
    rows: int = 10,
    title: str = "Dataset Preview",
    tablefmt: str = "grid"
) -> None:
    """Displays the first rows of the DataFrame in a formatted way.

    Args:
        df: DataFrame to display.
        rows: Number of rows to show.
        title: Table title.
        tablefmt: Table format (grid, fancy_grid, simple, etc.).
    """
    print(f"\n📊 {title}")
    print(f"{'─' * 80}")
    
    display_df = df.head(rows).copy()
    
    # Truncate long values
    for col in display_df.columns:
        if display_df[col].dtype == 'object':
            display_df[col] = display_df[col].astype(str).str[:30]
    
    print(tabulate(
        display_df,
        headers=display_df.columns,
        tablefmt=tablefmt,
        showindex=True,
        floatfmt=".2f"
    ))
    print()


def print_sales_summary(df: pd.DataFrame, title: str = "Sales Summary") -> None:
    """Displays sales summary (specific for e-commerce dataset)."""
    print(f"\n💰 {title}")
    print(f"{'─' * 80}")
    
    # Check for required columns
    required_cols = ['quantity', 'unitprice', 'total_amount']
    available_cols = [col for col in required_cols if col in df.columns]
    
    if not available_cols:
        print("⚠️  Sales columns not found\n")
        return
    
    sales_info = {
        'Metric': [],
        'Value': []
    }
    
    if 'quantity' in df.columns:
        sales_info['Metric'].append('Total Units Sold')
        sales_info['Value'].append(f"{df['quantity'].sum():,.0f}")
        sales_info['Metric'].append('Avg Quantity per Sale')
        sales_info['Value'].append(f"{df['quantity'].mean():.2f}")
    
    if 'unitprice' in df.columns:
        sales_info['Metric'].append('Avg Price')
        sales_info['Value'].append(f"${df['unitprice'].mean():.2f}")
        sales_info['Metric'].append('Price Range')
        sales_info['Value'].append(f"${df['unitprice'].min():.2f} - ${df['unitprice'].max():.2f}")
    
    if 'total_amount' in df.columns:
        sales_info['Metric'].append('Total Revenue')
        sales_info['Value'].append(f"${df['total_amount'].sum():,.2f}")
        sales_info['Metric'].append('Avg Revenue per Sale')
        sales_info['Value'].append(f"${df['total_amount'].mean():.2f}")
    
    print(tabulate(sales_info, headers='keys', tablefmt='grid'))
    print()


def print_data_summary(summary: dict) -> None:
    """Prints the `summary` generated by `get_data_summary` in a readable way."""
    print("\n🧾 CLEAN DATA SUMMARY")
    print("-" * 80)
    print(f"Rows: {summary['rows']:,}")
    print(f"Columns: {summary['cols']}")
    print(f"Memory: {summary['memory_mb']:.2f} MB")
    print(f"Duplicates: {summary['duplicates']:,}")

    # Show only columns with nulls
    nulls = {k: v for k, v in summary['nulls'].items() if v > 0}
    if nulls:
        print("\nNull values per column:")
        for col, cnt in nulls.items():
            print(f"   • {col}: {cnt:,}")
    else:
        print("\n✅ No null values detected")


def print_full_report(df: pd.DataFrame) -> None:
    """
    Compact and critical report: shows only transformed data and relevant issues
    (numeric errors, date errors, invalid sales, duplicates).
    """
    print(f"\n{'='*80}")
    print("🔎 CRITICAL DATA REPORT")
    print(f"{'='*80}")

    # Basic stats
    total_rows = len(df)
    total_cols = len(df.columns)
    memory_mb = df.memory_usage(deep=True).sum() / 1024**2
    null_pct = (df.isnull().sum().sum() / (total_rows * total_cols) * 100) if total_rows and total_cols else 0
    dup_count = df.duplicated().sum()

    basic = {
        'Metric': ['Rows', 'Columns', 'Memory (MB)', 'Nulls (%)', 'Duplicates'],
        'Value': [f"{total_rows:,}", total_cols, f"{memory_mb:.2f}", f"{null_pct:.2f}%", f"{dup_count:,}"]
    }
    print(tabulate(basic, headers='keys', tablefmt='grid'))

    # Invalid sales detection
    invalid_sales = pd.DataFrame()
    if 'quantity' in df.columns and 'unitprice' in df.columns:
        invalid_sales = df[(pd.to_numeric(df['quantity'], errors='coerce') <= 0) | (pd.to_numeric(df['unitprice'], errors='coerce') <= 0)]

    if not invalid_sales.empty:
        print(f"\n⚠️  Rows with invalid sales: {len(invalid_sales):,} (showing 5)")
        print(tabulate(invalid_sales.head(5), headers=invalid_sales.columns, tablefmt='grid', showindex=True, floatfmt='.2f'))
    else:
        print("\n✅ No invalid sales detected")

    # Numeric column issues
    numeric_candidates = [c for c in df.columns if any(k in c.lower() for k in ('qty', 'quantity', 'price', 'amount', 'total'))]
    numeric_issues = []
    for col in numeric_candidates:
        coerced = pd.to_numeric(df[col], errors='coerce')
        orig_nonnull = df[col].notna()
        coerced_na = coerced.isna() & orig_nonnull
        count_coerced = coerced_na.sum()
        if count_coerced > 0:
            numeric_issues.append((col, int(count_coerced)))

    if numeric_issues:
        issues_table = {'Column': [c for c, _ in numeric_issues], 'NaN Coercions': [n for _, n in numeric_issues]}
        print(f"\n⚠️  Numeric column issues (coercion):")
        print(tabulate(issues_table, headers='keys', tablefmt='grid'))
    else:
        print("\n✅ Critical numeric columns OK")

    # Date column issues
    date_candidates = [c for c in df.columns if 'date' in c.lower() or 'fecha' in c.lower()]
    date_issues = []
    for col in date_candidates:
        coerced = pd.to_datetime(df[col], errors='coerce')
        nat_count = coerced.isna().sum()
        if nat_count > 0:
            date_issues.append((col, int(nat_count)))

    if date_issues:
        date_table = {'Column': [c for c, _ in date_issues], 'Invalid (NaT)': [n for _, n in date_issues]}
        print(f"\n⚠️  Date column issues:")
        print(tabulate(date_table, headers='keys', tablefmt='grid'))
    else:
        if date_candidates:
            print("\n✅ Critical date columns OK")

    # Duplicates
    if dup_count:
        print(f"\n⚠️  Duplicates: {dup_count:,} (showing 3)")
        print(tabulate(df[df.duplicated(keep=False)].head(3), headers=df.columns, tablefmt='grid', showindex=True))

    # Compressed sales summary
    if any(c in df.columns for c in ('quantity', 'unitprice', 'total_amount')):
        print()
        print_sales_summary(df, title="Sales Summary (Compact)")

    # Data sample
    print_dataframe_head(df, rows=3, title="Sample Data (3 Rows)")

    print(f"{'='*80}\n")


def print_country_distribution(df: pd.DataFrame, top_n: int = 10) -> None:
    """Displays the distribution of records by country."""
    if 'country' not in df.columns:
        print("⚠️  'country' column not found for distribution analysis\n")
        return

    print(f"\n🌍 Top {top_n} Country Distribution")
    print(f"{'─' * 80}")
    
    dist = df['country'].value_counts().reset_index()
    dist.columns = ['Country', 'Count']
    dist['Percentage'] = (dist['Count'] / len(df) * 100).map("{:.2f}%".format)
    
    print(tabulate(dist.head(top_n), headers='keys', tablefmt='grid', showindex=False))
    print()
